# 基础镜像
FROM redis
# author
MAINTAINER blog

# 挂载目录
VOLUME /home/blog/redis
# 创建目录
RUN mkdir -p /home/blog/redis
# 指定路径
WORKDIR /home/blog/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/blog/redis/redis.conf
