# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER blog

# 挂载目录
VOLUME /home/blog
# 创建目录
RUN mkdir -p /home/blog
# 指定路径
WORKDIR /home/blog
# 复制jar文件到路径
COPY ./jar/blog-auth.jar /home/blog/blog-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","blog-auth.jar"]