# 基础镜像
FROM nginx
# author
MAINTAINER blog

# 挂载目录
VOLUME /home/blog/projects/blog-ui
# 创建目录
RUN mkdir -p /home/blog/projects/blog-ui
# 指定路径
WORKDIR /home/blog/projects/blog-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/blog/projects/blog-ui
